DELETE http://localhost:3002/api/blogs/8
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhvd2FyZDJAcG9vbWFpbC5wb28iLCJpZCI6MSwiaWF0IjoxNzI3NDMxMDU3fQ.0ZshTMjuKnjouYmUiRl-gDnFTnQS67Ctfr4E5QmZxq0