POST http://localhost:3002/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhvd2FyZDJAZW1haWwuY29tIiwiaWQiOjIsImlhdCI6MTcyODA2ODU0OH0.dAJfLIH6Zp22Bft_Q_tSWPqGijiDypy6VCXQFt8p0Kk

{
    "author": "An enabled user2",
    "title": "Testing X4",
    "url": "www.testX.com",
    "likes": 12,
    "year": 1991
}