POST http://localhost:3002/api/blogs
Content-Type: application/json

{
    "author": "Test man X",
    "title": "Test blog X",
    "url": "www.testX.com",
    "likes": "Wrong type",
    "mispelt field": "Superfluous"
}